export const GAME_CONSTANTS = {
  WIN_SCORE: 10,
  DRAW_SCORE: 3,
  LOSE_SCORE: 0,
  BOARD_SIZE: 9,
  GAME_ID: 'tic-tac-toe',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
