upstream auth_service       { server auth-service:3001; }
upstream leaderboard_service { server leaderboard-service:3002; }
upstream tictactoe_service   { server tic-tac-toe-service:3003; }
upstream guessnumber_service { server guess-number-service:3004; }
upstream frontend_service    { server frontend:80; }
